# GitHub Sponsors and other funders
# Surfaces a "Sponsor" button on the GitHub profile page (since this is the special
# username/username profile repo).
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: jyoti369
buy_me_a_coffee: jyoti369
# ko_fi: jyoti369
# polar: jyoti369
# custom: ['https://www.linkedin.com/in/jyoti369']
